In [1]:
## User Satisafaction Analysis

In [2]:
import pickle
import numpy as np
import pandas as pd
import math
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [3]:
user_engagement_df = pd.read_csv("C:/Users/dell/Desktop/user_engagement_data.csv")
user_engagement_df.head()

msisdn  cluster  XDR Sessions       dur      total_dv  newcluster
0  3.360100e+10        2             1  116720.0  8.786906e+08           3
1  3.360100e+10        1             1  181230.0  1.568596e+08           0
2  3.360100e+10        1             1  134969.0  5.959665e+08           0
3  3.360101e+10        1             1   49878.0  4.223207e+08           0
4  3.360101e+10        0             2   37104.0  1.457411e+09           4

In [5]:
user_experience_df = pd.read_csv("C:/Users/dell/Desktop/user_experience_data.csv")
user_experience_df.head()

MSISDN/Number  cluster  Total Avg RTT (ms)  Total Avg Bearer TP (kbps)  \
0   3.360100e+10        0                46.0                        76.0   
1   3.360100e+10        0                31.0                        99.0   
2   3.360100e+10        0                 0.0                        97.0   
3   3.360101e+10        0                84.0                       248.0   
4   3.360101e+10        1               119.0                     56844.0   

   Total TCP Retrans. Vol (Bytes)  
0                             0.0  
1                             0.0  
2                             0.0  
3                             0.0  
4                       9370832.0

## Engagement Score

In [7]:
eng_df = user_engagement_df.set_index('msisdn')[
    ['XDR Sessions', 'dur', 'total_dv']]

In [8]:
# scale data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(eng_df)
scaled_data

array([[-0.4812899 , -0.15801408,  0.38229732],
       [-0.4812899 ,  0.18814798, -1.08766633],
       [-0.4812899 , -0.06008955, -0.19345265],
       ...,
       [-0.4812899 ,  3.92373087, -0.93439522],
       [-0.4812899 ,  0.57342835, -0.19279826],
       [-0.4812899 ,  3.8832657 , -1.12372349]])

In [9]:
normalized_data = normalize(scaled_data)
normalized_data

array([[-0.75837458, -0.24898479,  0.60239071],
       [-0.39968156,  0.15624529, -0.90323976],
       [-0.92168892, -0.11507383, -0.37046937],
       ...,
       [-0.11848395,  0.96594411, -0.23002943],
       [-0.62257276,  0.74175848, -0.24939427],
       [-0.11822006,  0.95385314, -0.27602211]])

In [13]:
with open("C://Users//dell//Desktop//user_engagement.pkl", "rb") as f:
    kmeans1 = pickle.load(f)

In [15]:
less_engaged_cluster = 4

In [16]:
distance = kmeans1.fit_transform(normalized_data)
distance_from_less_engaged_cluster = list(
    map(lambda x: x[less_engaged_cluster], distance))
user_engagement_df['engagement_score'] = distance_from_less_engaged_cluster
user_engagement_df.head()

msisdn  cluster  XDR Sessions       dur      total_dv  newcluster  \
0  3.360100e+10        2             1  116720.0  8.786906e+08           3   
1  3.360100e+10        1             1  181230.0  1.568596e+08           0   
2  3.360100e+10        1             1  134969.0  5.959665e+08           0   
3  3.360101e+10        1             1   49878.0  4.223207e+08           0   
4  3.360101e+10        0             2   37104.0  1.457411e+09           4   

   engagement_score  
0          1.441545  
1          1.852355  
2          1.867126  
3          1.869914  
4          0.581456

## Exprience Score

In [17]:
exp_df = user_experience_df.set_index('MSISDN/Number')[
    ['Total Avg RTT (ms)', 'Total Avg Bearer TP (kbps)', 'Total TCP Retrans. Vol (Bytes)']]

In [18]:
# scale data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(exp_df)
scaled_data

array([[-0.14425818, -0.49274715, -0.0796073 ],
       [-0.16671505, -0.49220516, -0.0796073 ],
       [-0.21312591, -0.49225229, -0.0796073 ],
       ...,
       [-0.21312591, -0.49451452, -0.0796073 ],
       [-0.21312591, -0.49376044, -0.0796073 ],
       [-0.21312591, -0.49449095, -0.0796073 ]])

In [19]:
normalized_data = normalize(scaled_data)
normalized_data

array([[-0.27765199, -0.94838455, -0.15321921],
       [-0.3171086 , -0.93622317, -0.151421  ],
       [-0.39301507, -0.90773837, -0.14679992],
       ...,
       [-0.39153183, -0.90846847, -0.1462459 ],
       [-0.39202513, -0.90822602, -0.14643016],
       [-0.39154722, -0.90846091, -0.14625165]])

In [21]:
with open("C://Users//dell//Desktop//user_exp.pkl", "rb") as f:
    kmeans2 = pickle.load(f)

In [22]:
less_experience_cluster = 1

In [25]:
distance = kmeans2.fit_transform(normalized_data)
distance_from_less_experience_cluster = list(
    map(lambda x: x[less_experience_cluster], distance))
user_experience_df['experience_score'] = distance_from_less_experience_cluster
user_experience_df.head()

MSISDN/Number  cluster  Total Avg RTT (ms)  Total Avg Bearer TP (kbps)  \
0   3.360100e+10        0                46.0                        76.0   
1   3.360100e+10        0                31.0                        99.0   
2   3.360100e+10        0                 0.0                        97.0   
3   3.360101e+10        0                84.0                       248.0   
4   3.360101e+10        1               119.0                     56844.0   

   Total TCP Retrans. Vol (Bytes)  experience_score  
0                             0.0          1.855560  
1                             0.0          1.847765  
2                             0.0          1.830235  
3                             0.0          1.871880  
4                       9370832.0          0.130055